export const reports = [
  {
    date: "26 mai 2024",
    time: "10:45",
    entreprise: "Restaurant Teranga",
    type: "Restaurant",
    contact: "70 12 34 56",
    platform: "WhatsApp",
    agent: "agent Ouagadougou",
    interest: "Intéressé",
    notes: "Le patron veut voir des exemples de sites.",
  },
  {
    date: "26 mai 2024",
    time: "09:30",
    entreprise: "Power Gym",
    type: "Salle de sport",
    contact: "78 90 12 34",
    platform: "Appel",
    agent: "agent Ouagadougou",
    interest: "Veut plus d’informations",
    notes: "Prend contact pour plus d’éclairage.",
  },
  {
    date: "25 mai 2024",
    time: "16:20",
    entreprise: "Mèches d'Or",
    type: "Salon de coiffure",
    contact: "75 43 21 00",
    platform: "Instagram",
    agent: "Awa Traoré",
    interest: "Peut-être",
    notes: "Hésite encore sur le prix.",
  },
  {
    date: "25 mai 2024",
    time: "11:15",
    entreprise: "Le Saveur Ivoirienne",
    type: "Restaurant",
    contact: "77 65 43 21",
    platform: "WhatsApp",
    agent: "Awa Traoré",
    interest: "Intéressé",
    notes: "Va vous contacter prochainement.",
  },
];
